#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 官方博客：http://www.cnblogs.com/huyong
//           http://blog.csdn.net/chinahuyong
//    Email：80368704@qq.com
//       QQ：80368704
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System.Collections.Generic;
using System.Globalization;

namespace RDIFramework.BizLogic
{
    using RDIFramework.Utilities;

    /// <summary>
    /// AccreditUserManager
    /// 
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 EricHu 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>EricHu</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class AccreditUserManager : DbCommonManager
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public AccreditUserManager()
        {
            base.CurrentTableName = AccreditUserTable.TableName;
            base.PrimaryKey = AccreditUserTable.FieldAUserId;
        }

        /// <summary>
        /// 构造函数
        /// <param name="tableName">指定表名</param>
        /// </summary>
        public AccreditUserManager(string tableName)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        public AccreditUserManager(IDbProvider dbProvider): this()
        {
            DBProvider = dbProvider;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="userInfo">用户信息</param>
        public AccreditUserManager(UserInfo userInfo) : this()
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        public AccreditUserManager(IDbProvider dbProvider, UserInfo userInfo) : this(dbProvider)
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        /// <param name="tableName">指定表名</param>
        public AccreditUserManager(IDbProvider dbProvider, UserInfo userInfo, string tableName) : this(dbProvider, userInfo)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="accreditUserEntity">实体</param>
        /// <returns>主键</returns>
        public string Add(AccreditUserEntity accreditUserEntity)
        {
            return this.AddEntity(accreditUserEntity);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="accreditUserEntity">实体</param>
        /// <param name="identity">自增量方式</param>
        /// <param name="returnId">返回主键</param>
        /// <returns>主键</returns>
        public string Add(AccreditUserEntity accreditUserEntity, bool identity, bool returnId)
        {
            this.Identity = identity;
            this.ReturnId = returnId;
            return this.AddEntity(accreditUserEntity);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <param name="accreditUserEntity">实体</param>
        public int Update(AccreditUserEntity accreditUserEntity)
        {
            return this.UpdateEntity(accreditUserEntity);
        }

        /// <summary>
        /// 获取实体
        /// </summary>
        /// <param name="id">主键</param>
        public AccreditUserEntity GetEntity(string id)
        {
            return BaseEntity.Create<AccreditUserEntity>(this.GetDT(new KeyValuePair<string, object>(AccreditUserTable.FieldAUserId, id)));
        }

        /// <summary>
        /// 添加实体
        /// </summary>
        /// <param name="accreditUserEntity">实体</param>
        public string AddEntity(AccreditUserEntity accreditUserEntity)
        {
            var sequence = string.Empty;
            this.Identity = false; 
            if (accreditUserEntity.AUserId != null)
            {
                sequence = accreditUserEntity.AUserId.ToString();
            }
            var sqlBuilder = new SQLBuilder(DBProvider, this.Identity, this.ReturnId);
            sqlBuilder.BeginInsert(this.CurrentTableName, AccreditUserTable.FieldAUserId);
            if (!this.Identity) 
            {
                if (string.IsNullOrEmpty(accreditUserEntity.AUserId)) 
                { 
                    sequence = BusinessLogic.NewGuid(); 
                    accreditUserEntity.AUserId = sequence ;
                }
                sqlBuilder.SetValue(AccreditUserTable.FieldAUserId, accreditUserEntity.AUserId);
            }
            else
            {
                if (!this.ReturnId && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                {
                    if (DBProvider.CurrentDbType == CurrentDbType.Oracle)
                    {
                        sqlBuilder.SetFormula(AccreditUserTable.FieldAUserId, "SEQ_" + this.CurrentTableName.ToUpper() + ".NEXTVAL ");
                    }
                    if (DBProvider.CurrentDbType == CurrentDbType.DB2)
                    {
                        sqlBuilder.SetFormula(AccreditUserTable.FieldAUserId, "NEXT VALUE FOR SEQ_" + this.CurrentTableName.ToUpper());
                    }
                }
                else
                {
                    if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                    {
                        if (string.IsNullOrEmpty(accreditUserEntity.AUserId))
                        {
                            if (string.IsNullOrEmpty(sequence))
                            {
                                var sequenceManager = new CiSequenceManager(DBProvider, this.Identity);
                                sequence = sequenceManager.GetSequence(this.CurrentTableName);
                            }
                            accreditUserEntity.AUserId = sequence;
                        }
                        sqlBuilder.SetValue(AccreditUserTable.FieldAUserId, accreditUserEntity.AUserId);
                    }
                }
            }
            this.SetEntity(sqlBuilder, accreditUserEntity);
            if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.SqlServer || DBProvider.CurrentDbType == CurrentDbType.Access))
            {
                sequence = sqlBuilder.EndInsert().ToString(CultureInfo.InvariantCulture);
            }
            else
            {
                sqlBuilder.EndInsert();
            }
            return sequence;
        }

        /// <summary>
        /// 更新实体
        /// </summary>
        /// <param name="accreditUserEntity">实体</param>
        public int UpdateEntity(AccreditUserEntity accreditUserEntity)
        {
            var sqlBuilder = new SQLBuilder(DBProvider);
            sqlBuilder.BeginUpdate(this.CurrentTableName);
            this.SetEntity(sqlBuilder, accreditUserEntity);
            sqlBuilder.SetWhere(AccreditUserTable.FieldAUserId, accreditUserEntity.AUserId);
            return sqlBuilder.EndUpdate();
        }

        /// <summary>
        /// 设置实体
        /// </summary>
        /// <param name="sqlBuilder"></param>
        /// <param name="accreditUserEntity">实体</param>
        private void SetEntity(SQLBuilder sqlBuilder, AccreditUserEntity accreditUserEntity)
        {
            sqlBuilder.SetValue(AccreditUserTable.FieldAccreditFromUserId, accreditUserEntity.AccreditFromUserId);
            sqlBuilder.SetValue(AccreditUserTable.FieldAccreditToUserId, accreditUserEntity.AccreditToUserId);
            sqlBuilder.SetValue(AccreditUserTable.FieldAccreditDateTime, accreditUserEntity.AccreditDateTime);
            sqlBuilder.SetValue(AccreditUserTable.FieldAccreditStatus, accreditUserEntity.AccreditStatus);
            sqlBuilder.SetValue(AccreditUserTable.FieldAcWorkflowId, accreditUserEntity.AcWorkflowId);
            sqlBuilder.SetValue(AccreditUserTable.FieldAcWorktaskId, accreditUserEntity.AcWorktaskId);
        }

        /// <summary>
        /// 删除实体
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>影响行数</returns>
        public int Delete(string id)
        {
            return this.Delete(new KeyValuePair<string, object>(AccreditUserTable.FieldAUserId, id));
        }
    }
}
