#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 官方博客：http://www.cnblogs.com/huyong
//           http://blog.csdn.net/chinahuyong
//    Email：80368704@qq.com
//       QQ：80368704
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System.Collections.Generic;

namespace RDIFramework.BizLogic
{
    
    using RDIFramework.Utilities;

    /// <summary>
    /// OperatorInstanceManager
    /// 处理者实例
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 EricHu 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>EricHu</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class OperatorInstanceManager : DbCommonManager
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public OperatorInstanceManager()
        {
            base.CurrentTableName = OperatorInstanceTable.TableName;
            base.PrimaryKey = OperatorInstanceTable.FieldOperatorInsId;
        }

        /// <summary>
        /// 构造函数
        /// <param name="tableName">指定表名</param>
        /// </summary>
        public OperatorInstanceManager(string tableName)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        public OperatorInstanceManager(IDbProvider dbProvider): this()
        {
            DBProvider = dbProvider;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="userInfo">用户信息</param>
        public OperatorInstanceManager(UserInfo userInfo) : this()
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        public OperatorInstanceManager(IDbProvider dbProvider, UserInfo userInfo) : this(dbProvider)
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        /// <param name="tableName">指定表名</param>
        public OperatorInstanceManager(IDbProvider dbProvider, UserInfo userInfo, string tableName) : this(dbProvider, userInfo)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="operatorInstanceEntity">实体</param>
        /// <returns>主键</returns>
        public string Add(OperatorInstanceEntity operatorInstanceEntity)
        {
            return this.AddEntity(operatorInstanceEntity);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="operatorInstanceEntity">实体</param>
        /// <param name="identity">自增量方式</param>
        /// <param name="returnId">返回主键</param>
        /// <returns>主键</returns>
        public string Add(OperatorInstanceEntity operatorInstanceEntity, bool identity, bool returnId)
        {
            this.Identity = identity;
            this.ReturnId = returnId;
            return this.AddEntity(operatorInstanceEntity);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <param name="operatorInstanceEntity">实体</param>
        public int Update(OperatorInstanceEntity operatorInstanceEntity)
        {
            return this.UpdateEntity(operatorInstanceEntity);
        }

        /// <summary>
        /// 获取实体
        /// </summary>
        /// <param name="id">主键</param>
        public OperatorInstanceEntity GetEntity(string id)
        {
            var operatorInstanceEntity = BaseEntity.Create<OperatorInstanceEntity>(this.GetDT(new KeyValuePair<string, object>(OperatorInstanceTable.FieldOperatorInsId, id)));
            return operatorInstanceEntity;
        }

        /// <summary>
        /// 添加实体
        /// </summary>
        /// <param name="operatorInstanceEntity">实体</param>
        public string AddEntity(OperatorInstanceEntity operatorInstanceEntity)
        {
            var sequence = string.Empty;
            this.Identity = false; 
            if (operatorInstanceEntity.OperatorInsId != null)
            {
                sequence = operatorInstanceEntity.OperatorInsId.ToString();
            }
            var sqlBuilder = new SQLBuilder(DBProvider, this.Identity, this.ReturnId);
            sqlBuilder.BeginInsert(this.CurrentTableName, OperatorInstanceTable.FieldOperatorInsId);
            if (!this.Identity) 
            {
                if (string.IsNullOrEmpty(operatorInstanceEntity.OperatorInsId)) 
                { 
                    sequence = BusinessLogic.NewGuid(); 
                    operatorInstanceEntity.OperatorInsId = sequence ;
                }
                sqlBuilder.SetValue(OperatorInstanceTable.FieldOperatorInsId, operatorInstanceEntity.OperatorInsId);
            }
            else
            {
                if (!this.ReturnId && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                {
                    if (DBProvider.CurrentDbType == CurrentDbType.Oracle)
                    {
                        sqlBuilder.SetFormula(OperatorInstanceTable.FieldOperatorInsId, "SEQ_" + this.CurrentTableName.ToUpper() + ".NEXTVAL ");
                    }
                    if (DBProvider.CurrentDbType == CurrentDbType.DB2)
                    {
                        sqlBuilder.SetFormula(OperatorInstanceTable.FieldOperatorInsId, "NEXT VALUE FOR SEQ_" + this.CurrentTableName.ToUpper());
                    }
                }
                else
                {
                    if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                    {
                        if (string.IsNullOrEmpty(operatorInstanceEntity.OperatorInsId))
                        {
                            if (string.IsNullOrEmpty(sequence))
                            {
                                var sequenceManager = new CiSequenceManager(DBProvider, this.Identity);
                                sequence = sequenceManager.GetSequence(this.CurrentTableName);
                            }
                            operatorInstanceEntity.OperatorInsId = sequence;
                        }
                        sqlBuilder.SetValue(OperatorInstanceTable.FieldOperatorInsId, operatorInstanceEntity.OperatorInsId);
                    }
                }
            }
            this.SetEntity(sqlBuilder, operatorInstanceEntity);
            if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.SqlServer || DBProvider.CurrentDbType == CurrentDbType.Access))
            {
                sequence = sqlBuilder.EndInsert().ToString();
            }
            else
            {
                sqlBuilder.EndInsert();
            }
            return sequence;
        }

        /// <summary>
        /// 更新实体
        /// </summary>
        /// <param name="operatorInstanceEntity">实体</param>
        public int UpdateEntity(OperatorInstanceEntity operatorInstanceEntity)
        {
            var sqlBuilder = new SQLBuilder(DBProvider);
            sqlBuilder.BeginUpdate(this.CurrentTableName);
            this.SetEntity(sqlBuilder, operatorInstanceEntity);
            sqlBuilder.SetWhere(OperatorInstanceTable.FieldOperatorInsId, operatorInstanceEntity.OperatorInsId);
            return sqlBuilder.EndUpdate();
        }

        /// <summary>
        /// 设置实体
        /// </summary>
        /// <param name="operatorInstanceEntity">实体</param>
        private void SetEntity(SQLBuilder sqlBuilder, OperatorInstanceEntity operatorInstanceEntity)
        {
            sqlBuilder.SetValue(OperatorInstanceTable.FieldWorkFlowId, operatorInstanceEntity.WorkFlowId);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldWorkTaskId, operatorInstanceEntity.WorkTaskId);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldWorkFlowInsId, operatorInstanceEntity.WorkFlowInsId);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldWorkTaskInsId, operatorInstanceEntity.WorkTaskInsId);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldUserId, operatorInstanceEntity.UserId);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldOperType, operatorInstanceEntity.OperType);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldOperRealtion, operatorInstanceEntity.OperRealtion);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldOperContent, operatorInstanceEntity.OperContent);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldOperContentText, operatorInstanceEntity.OperContentText);
            sqlBuilder.SetValue(OperatorInstanceTable.FieldOperStatus, operatorInstanceEntity.OperStatus);
            if (DBProvider.CurrentDbType == CurrentDbType.Oracle)
            {
                sqlBuilder.SetValue(OperatorInstanceTable.FieldOperDateTime, operatorInstanceEntity.OperDateTime != null ? BusinessLogic.GetOracleDateFormat(System.DateTime.Parse(operatorInstanceEntity.OperDateTime.ToString()), "yyyy-mm-dd hh24:mi:ss") : operatorInstanceEntity.OperDateTime);
            }
            else
            {
                sqlBuilder.SetValue(OperatorInstanceTable.FieldOperDateTime, operatorInstanceEntity.OperDateTime);
            }

            sqlBuilder.SetValue(OperatorInstanceTable.FieldChangeOperator, operatorInstanceEntity.ChangeOperator);
        }

        /// <summary>
        /// 删除实体
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>影响行数</returns>
        public int Delete(string id)
        {
            return this.Delete(new KeyValuePair<string, object>(OperatorInstanceTable.FieldOperatorInsId, id));
        }
    }
}
