#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 官方博客：http://www.cnblogs.com/huyong
//           http://blog.csdn.net/chinahuyong
//    Email：80368704@qq.com
//       QQ：80368704
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System.Collections.Generic;
using System.Globalization;

namespace RDIFramework.BizLogic
{
    
    using RDIFramework.Utilities;

    /// <summary>
    /// WorkFlowEventManager
    /// 事件通知
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 EricHu 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>EricHu</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class WorkFlowEventManager : DbCommonManager
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public WorkFlowEventManager()
        {
            base.CurrentTableName = WorkFlowEventTable.TableName;
            base.PrimaryKey = WorkFlowEventTable.FieldGuid;
        }

        /// <summary>
        /// 构造函数
        /// <param name="tableName">指定表名</param>
        /// </summary>
        public WorkFlowEventManager(string tableName)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        public WorkFlowEventManager(IDbProvider dbProvider): this()
        {
            DBProvider = dbProvider;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="userInfo">用户信息</param>
        public WorkFlowEventManager(UserInfo userInfo) : this()
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        public WorkFlowEventManager(IDbProvider dbProvider, UserInfo userInfo) : this(dbProvider)
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        /// <param name="tableName">指定表名</param>
        public WorkFlowEventManager(IDbProvider dbProvider, UserInfo userInfo, string tableName) : this(dbProvider, userInfo)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="workFlowEventEntity">实体</param>
        /// <returns>主键</returns>
        public string Add(WorkFlowEventEntity workFlowEventEntity)
        {
            return this.AddEntity(workFlowEventEntity);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="workFlowEventEntity">实体</param>
        /// <param name="identity">自增量方式</param>
        /// <param name="returnId">返回主键</param>
        /// <returns>主键</returns>
        public string Add(WorkFlowEventEntity workFlowEventEntity, bool identity, bool returnId)
        {
            this.Identity = identity;
            this.ReturnId = returnId;
            return this.AddEntity(workFlowEventEntity);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <param name="workFlowEventEntity">实体</param>
        public int Update(WorkFlowEventEntity workFlowEventEntity)
        {
            return this.UpdateEntity(workFlowEventEntity);
        }

        /// <summary>
        /// 获取实体
        /// </summary>
        /// <param name="id">主键</param>
        public WorkFlowEventEntity GetEntity(string id)
        {
            var workFlowEventEntity = BaseEntity.Create<WorkFlowEventEntity>(this.GetDT(new KeyValuePair<string, object>(WorkFlowEventTable.FieldGuid, id)));
            return workFlowEventEntity;
        }

        /// <summary>
        /// 添加实体
        /// </summary>
        /// <param name="workFlowEventEntity">实体</param>
        public string AddEntity(WorkFlowEventEntity workFlowEventEntity)
        {
            string sequence = string.Empty;
            this.Identity = false; 
            if ( !string.IsNullOrEmpty(workFlowEventEntity.Guid))
            {
                sequence = workFlowEventEntity.Guid.ToString(CultureInfo.InvariantCulture);
            }
            SQLBuilder sqlBuilder = new SQLBuilder(DBProvider, this.Identity, this.ReturnId);
            sqlBuilder.BeginInsert(this.CurrentTableName, WorkFlowEventTable.FieldGuid);
            if (!this.Identity) 
            {
                if (string.IsNullOrEmpty(workFlowEventEntity.Guid)) 
                { 
                    sequence = BusinessLogic.NewGuid(); 
                    workFlowEventEntity.Guid = sequence ;
                }
                sqlBuilder.SetValue(WorkFlowEventTable.FieldGuid, workFlowEventEntity.Guid);
            }
            else
            {
                if (!this.ReturnId && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                {
                    if (DBProvider.CurrentDbType == CurrentDbType.Oracle)
                    {
                        sqlBuilder.SetFormula(WorkFlowEventTable.FieldGuid, "SEQ_" + this.CurrentTableName.ToUpper() + ".NEXTVAL ");
                    }
                    if (DBProvider.CurrentDbType == CurrentDbType.DB2)
                    {
                        sqlBuilder.SetFormula(WorkFlowEventTable.FieldGuid, "NEXT VALUE FOR SEQ_" + this.CurrentTableName.ToUpper());
                    }
                }
                else
                {
                    if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                    {
                        if (string.IsNullOrEmpty(workFlowEventEntity.Guid))
                        {
                            if (string.IsNullOrEmpty(sequence))
                            {
                                CiSequenceManager sequenceManager = new CiSequenceManager(DBProvider, this.Identity);
                                sequence = sequenceManager.GetSequence(this.CurrentTableName);
                            }
                            workFlowEventEntity.Guid = sequence;
                        }
                        sqlBuilder.SetValue(WorkFlowEventTable.FieldGuid, workFlowEventEntity.Guid);
                    }
                }
            }
            this.SetEntity(sqlBuilder, workFlowEventEntity);
            if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.SqlServer || DBProvider.CurrentDbType == CurrentDbType.Access))
            {
                sequence = sqlBuilder.EndInsert().ToString(CultureInfo.InvariantCulture);
            }
            else
            {
                sqlBuilder.EndInsert();
            }
            return sequence;
        }

        /// <summary>
        /// 更新实体
        /// </summary>
        /// <param name="workFlowEventEntity">实体</param>
        public int UpdateEntity(WorkFlowEventEntity workFlowEventEntity)
        {
            SQLBuilder sqlBuilder = new SQLBuilder(DBProvider);
            sqlBuilder.BeginUpdate(this.CurrentTableName);
            this.SetEntity(sqlBuilder, workFlowEventEntity);
            sqlBuilder.SetWhere(WorkFlowEventTable.FieldGuid, workFlowEventEntity.Guid);
            return sqlBuilder.EndUpdate();
        }

        /// <summary>
        /// 设置实体
        /// </summary>
        /// <param name="sqlBuilder">Sql语句生成器</param>
        /// <param name="workFlowEventEntity">实体</param>
        private void SetEntity(SQLBuilder sqlBuilder, WorkFlowEventEntity workFlowEventEntity)
        {
            sqlBuilder.SetValue(WorkFlowEventTable.FieldWorkFlowId, workFlowEventEntity.WorkFlowId);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldWorkTaskId, workFlowEventEntity.WorkTaskId);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldRemark, workFlowEventEntity.Remark);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldOtSms, workFlowEventEntity.OtSms);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldOtMsg, workFlowEventEntity.OtMsg);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldOtEmail, workFlowEventEntity.OtEmail);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldRmSms, workFlowEventEntity.RmSms);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldRmMsg, workFlowEventEntity.RmMsg);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldRmEmail, workFlowEventEntity.RmEmail);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldOtToUsers, workFlowEventEntity.OtToUsers);
            sqlBuilder.SetValue(WorkFlowEventTable.FieldRmToUsers, workFlowEventEntity.RmToUsers);
        }

        /// <summary>
        /// 删除实体
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>影响行数</returns>
        public int Delete(string id)
        {
            return this.Delete(new KeyValuePair<string, object>(WorkFlowEventTable.FieldGuid, id));
        }
    }
}
