#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 官方博客：http://www.cnblogs.com/huyong
//           http://blog.csdn.net/chinahuyong
//    Email：80368704@qq.com
//       QQ：80368704
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System.Collections.Generic;
using System.Globalization;

namespace RDIFramework.BizLogic
{
    
    using RDIFramework.Utilities;

    /// <summary>
    /// WorkServiceMessageManager
    /// 
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 XuWangBin 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>XuWangBin</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class WorkServiceMessageManager : DbCommonManager
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public WorkServiceMessageManager()
        {
            base.CurrentTableName = WorkServiceMessageTable.TableName;
            base.PrimaryKey = WorkServiceMessageTable.FieldMessageId;
        }

        /// <summary>
        /// 构造函数
        /// <param name="tableName">指定表名</param>
        /// </summary>
        public WorkServiceMessageManager(string tableName)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        public WorkServiceMessageManager(IDbProvider dbProvider): this()
        {
            DBProvider = dbProvider;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="userInfo">用户信息</param>
        public WorkServiceMessageManager(UserInfo userInfo) : this()
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        public WorkServiceMessageManager(IDbProvider dbProvider, UserInfo userInfo) : this(dbProvider)
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        /// <param name="tableName">指定表名</param>
        public WorkServiceMessageManager(IDbProvider dbProvider, UserInfo userInfo, string tableName) : this(dbProvider, userInfo)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="workServiceMessageEntity">实体</param>
        /// <returns>主键</returns>
        public string Add(WorkServiceMessageEntity workServiceMessageEntity)
        {
            return this.AddEntity(workServiceMessageEntity);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="workServiceMessageEntity">实体</param>
        /// <param name="identity">自增量方式</param>
        /// <param name="returnId">返回主键</param>
        /// <returns>主键</returns>
        public string Add(WorkServiceMessageEntity workServiceMessageEntity, bool identity, bool returnId)
        {
            this.Identity = identity;
            this.ReturnId = returnId;
            return this.AddEntity(workServiceMessageEntity);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <param name="workServiceMessageEntity">实体</param>
        public int Update(WorkServiceMessageEntity workServiceMessageEntity)
        {
            return this.UpdateEntity(workServiceMessageEntity);
        }

        /// <summary>
        /// 获取实体
        /// </summary>
        /// <param name="id">主键</param>
        public WorkServiceMessageEntity GetEntity(string id)
        {
            return BaseEntity.Create<WorkServiceMessageEntity>(this.GetDT(new KeyValuePair<string, object>(WorkServiceMessageTable.FieldMessageId, id)));
        }

        /// <summary>
        /// 添加实体
        /// </summary>
        /// <param name="workServiceMessageEntity">实体</param>
        public string AddEntity(WorkServiceMessageEntity workServiceMessageEntity)
        {
            var sequence = string.Empty;
            this.Identity = false; 
            if ( !string.IsNullOrEmpty(workServiceMessageEntity.MessageId))
            {
                sequence = workServiceMessageEntity.MessageId.ToString(CultureInfo.InvariantCulture);
            }
            var sqlBuilder = new SQLBuilder(DBProvider, this.Identity, this.ReturnId);
            sqlBuilder.BeginInsert(this.CurrentTableName, WorkServiceMessageTable.FieldMessageId);
            if (!this.Identity) 
            {
                if (string.IsNullOrEmpty(workServiceMessageEntity.MessageId)) 
                { 
                    sequence = BusinessLogic.NewGuid(); 
                    workServiceMessageEntity.MessageId = sequence ;
                }
                sqlBuilder.SetValue(WorkServiceMessageTable.FieldMessageId, workServiceMessageEntity.MessageId);
            }
            else
            {
                if (!this.ReturnId && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                {
                    if (DBProvider.CurrentDbType == CurrentDbType.Oracle)
                    {
                        sqlBuilder.SetFormula(WorkServiceMessageTable.FieldMessageId, "SEQ_" + this.CurrentTableName.ToUpper() + ".NEXTVAL ");
                    }
                    if (DBProvider.CurrentDbType == CurrentDbType.DB2)
                    {
                        sqlBuilder.SetFormula(WorkServiceMessageTable.FieldMessageId, "NEXT VALUE FOR SEQ_" + this.CurrentTableName.ToUpper());
                    }
                }
                else
                {
                    if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                    {
                        if (string.IsNullOrEmpty(workServiceMessageEntity.MessageId))
                        {
                            if (string.IsNullOrEmpty(sequence))
                            {
                                var sequenceManager = new CiSequenceManager(DBProvider, this.Identity);
                                sequence = sequenceManager.GetSequence(this.CurrentTableName);
                            }
                            workServiceMessageEntity.MessageId = sequence;
                        }
                        sqlBuilder.SetValue(WorkServiceMessageTable.FieldMessageId, workServiceMessageEntity.MessageId);
                    }
                }
            }
            this.SetEntity(sqlBuilder, workServiceMessageEntity);
            sqlBuilder.SetDBNow(WorkServiceMessageTable.FieldCreateTime);
            if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.SqlServer || DBProvider.CurrentDbType == CurrentDbType.Access))
            {
                sequence = sqlBuilder.EndInsert().ToString(CultureInfo.InvariantCulture);
            }
            else
            {
                sqlBuilder.EndInsert();
            }
            return sequence;
        }

        /// <summary>
        /// 更新实体
        /// </summary>
        /// <param name="workServiceMessageEntity">实体</param>
        public int UpdateEntity(WorkServiceMessageEntity workServiceMessageEntity)
        {
            var sqlBuilder = new SQLBuilder(DBProvider);
            sqlBuilder.BeginUpdate(this.CurrentTableName);
            this.SetEntity(sqlBuilder, workServiceMessageEntity);
            sqlBuilder.SetWhere(WorkServiceMessageTable.FieldMessageId, workServiceMessageEntity.MessageId);
            return sqlBuilder.EndUpdate();
        }

        /// <summary>
        /// 设置实体
        /// </summary>
        /// <param name="sqlBuilder">Sql语句生成器</param>
        /// <param name="workServiceMessageEntity">实体</param>
        private void SetEntity(SQLBuilder sqlBuilder, WorkServiceMessageEntity workServiceMessageEntity)
        {
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldWorkFlowId, workServiceMessageEntity.WorkFlowId);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldWorkTaskId, workServiceMessageEntity.WorkTaskId);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldWorkflowInsId, workServiceMessageEntity.WorkflowInsId);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldWorktaskInsId, workServiceMessageEntity.WorktaskInsId);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldContent, workServiceMessageEntity.Content);
            if (DBProvider.CurrentDbType == CurrentDbType.Oracle)
            {
                sqlBuilder.SetValue(WorkServiceMessageTable.FieldSendTime1, workServiceMessageEntity.SendTime1 != null ? BusinessLogic.GetOracleDateFormat(System.DateTime.Parse(workServiceMessageEntity.SendTime1.ToString()), "yyyy-mm-dd hh24:mi:ss") : workServiceMessageEntity.SendTime1);
                sqlBuilder.SetValue(WorkServiceMessageTable.FieldSendTime2, workServiceMessageEntity.SendTime2 != null ? BusinessLogic.GetOracleDateFormat(System.DateTime.Parse(workServiceMessageEntity.SendTime2.ToString()), "yyyy-mm-dd hh24:mi:ss") : workServiceMessageEntity.SendTime2);
                sqlBuilder.SetValue(WorkServiceMessageTable.FieldSendTime3, workServiceMessageEntity.SendTime3 != null ? BusinessLogic.GetOracleDateFormat(System.DateTime.Parse(workServiceMessageEntity.SendTime3.ToString()), "yyyy-mm-dd hh24:mi:ss") : workServiceMessageEntity.SendTime3);
            }
            else
            {
                sqlBuilder.SetValue(WorkServiceMessageTable.FieldSendTime1, workServiceMessageEntity.SendTime1);
                sqlBuilder.SetValue(WorkServiceMessageTable.FieldSendTime2, workServiceMessageEntity.SendTime2);
                sqlBuilder.SetValue(WorkServiceMessageTable.FieldSendTime3, workServiceMessageEntity.SendTime3);
            }

            sqlBuilder.SetValue(WorkServiceMessageTable.FieldDoneFlag1, workServiceMessageEntity.DoneFlag1);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldDoneFlag2, workServiceMessageEntity.DoneFlag2);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldDoneFlag3, workServiceMessageEntity.DoneFlag3);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldMsgType, workServiceMessageEntity.MsgType);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldUsers1, workServiceMessageEntity.Users1);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldUsers2, workServiceMessageEntity.Users2);
            sqlBuilder.SetValue(WorkServiceMessageTable.FieldUsers3, workServiceMessageEntity.Users3);
        }

        /// <summary>
        /// 删除实体
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>影响行数</returns>
        public int Delete(string id)
        {
            return this.Delete(new KeyValuePair<string, object>(WorkServiceMessageTable.FieldMessageId, id));
        }
    }
}
