#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 官方博客：http://www.cnblogs.com/huyong
//           http://blog.csdn.net/chinahuyong
//    Email：80368704@qq.com
//       QQ：80368704
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System.Collections.Generic;
using System.Globalization;

namespace RDIFramework.BizLogic
{    
    using RDIFramework.Utilities;

    /// <summary>
    /// WorkLinkManager
    /// 流程连线配置
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 EricHu 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>EricHu</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class WorkLinkManager : DbCommonManager
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public WorkLinkManager()
        {
            base.CurrentTableName = WorkLinkTable.TableName;
            base.PrimaryKey = WorkLinkTable.FieldWorkLinkId;
        }

        /// <summary>
        /// 构造函数
        /// <param name="tableName">指定表名</param>
        /// </summary>
        public WorkLinkManager(string tableName)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        public WorkLinkManager(IDbProvider dbProvider): this()
        {
            DBProvider = dbProvider;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="userInfo">用户信息</param>
        public WorkLinkManager(UserInfo userInfo) : this()
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        public WorkLinkManager(IDbProvider dbProvider, UserInfo userInfo) : this(dbProvider)
        {
            UserInfo = userInfo;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dbProvider">数据库连接</param>
        /// <param name="userInfo">用户信息</param>
        /// <param name="tableName">指定表名</param>
        public WorkLinkManager(IDbProvider dbProvider, UserInfo userInfo, string tableName) : this(dbProvider, userInfo)
        {
            base.CurrentTableName = tableName;
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="workLinkEntity">实体</param>
        /// <returns>主键</returns>
        public string Add(WorkLinkEntity workLinkEntity)
        {
            return this.AddEntity(workLinkEntity);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="workLinkEntity">实体</param>
        /// <param name="identity">自增量方式</param>
        /// <param name="returnId">返回主键</param>
        /// <returns>主键</returns>
        public string Add(WorkLinkEntity workLinkEntity, bool identity, bool returnId)
        {
            this.Identity = identity;
            this.ReturnId = returnId;
            return this.AddEntity(workLinkEntity);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <param name="workLinkEntity">实体</param>
        public int Update(WorkLinkEntity workLinkEntity)
        {
            return this.UpdateEntity(workLinkEntity);
        }

        /// <summary>
        /// 获取实体
        /// </summary>
        /// <param name="id">主键</param>
        public WorkLinkEntity GetEntity(string id)
        {
            return BaseEntity.Create<WorkLinkEntity>(this.GetDT(new KeyValuePair<string, object>(WorkLinkTable.FieldWorkLinkId, id)));
        }

        /// <summary>
        /// 添加实体
        /// </summary>
        /// <param name="workLinkEntity">实体</param>
        public string AddEntity(WorkLinkEntity workLinkEntity)
        {
            string sequence = string.Empty;
            this.Identity = false; 
            if ( !string.IsNullOrEmpty(workLinkEntity.WorkLinkId))
            {
                sequence = workLinkEntity.WorkLinkId.ToString(CultureInfo.InvariantCulture);
            }
            SQLBuilder sqlBuilder = new SQLBuilder(DBProvider, this.Identity, this.ReturnId);
            sqlBuilder.BeginInsert(this.CurrentTableName, WorkLinkTable.FieldWorkLinkId);
            if (!this.Identity) 
            {
                if (string.IsNullOrEmpty(workLinkEntity.WorkLinkId)) 
                { 
                    sequence = BusinessLogic.NewGuid(); 
                    workLinkEntity.WorkLinkId = sequence ;
                }
                sqlBuilder.SetValue(WorkLinkTable.FieldWorkLinkId, workLinkEntity.WorkLinkId);
            }
            else
            {
                if (!this.ReturnId && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                {
                    if (DBProvider.CurrentDbType == CurrentDbType.Oracle)
                    {
                        sqlBuilder.SetFormula(WorkLinkTable.FieldWorkLinkId, "SEQ_" + this.CurrentTableName.ToUpper() + ".NEXTVAL ");
                    }
                    if (DBProvider.CurrentDbType == CurrentDbType.DB2)
                    {
                        sqlBuilder.SetFormula(WorkLinkTable.FieldWorkLinkId, "NEXT VALUE FOR SEQ_" + this.CurrentTableName.ToUpper());
                    }
                }
                else
                {
                    if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.Oracle || DBProvider.CurrentDbType == CurrentDbType.DB2))
                    {
                        if (string.IsNullOrEmpty(workLinkEntity.WorkLinkId))
                        {
                            if (string.IsNullOrEmpty(sequence))
                            {
                                CiSequenceManager sequenceManager = new CiSequenceManager(DBProvider, this.Identity);
                                sequence = sequenceManager.GetSequence(this.CurrentTableName);
                            }
                            workLinkEntity.WorkLinkId = sequence;
                        }
                        sqlBuilder.SetValue(WorkLinkTable.FieldWorkLinkId, workLinkEntity.WorkLinkId);
                    }
                }
            }
            this.SetEntity(sqlBuilder, workLinkEntity);
            if (this.Identity && (DBProvider.CurrentDbType == CurrentDbType.SqlServer || DBProvider.CurrentDbType == CurrentDbType.Access))
            {
                sequence = sqlBuilder.EndInsert().ToString();
            }
            else
            {
                sqlBuilder.EndInsert();
            }
            return sequence;
        }

        /// <summary>
        /// 更新实体
        /// </summary>
        /// <param name="workLinkEntity">实体</param>
        public int UpdateEntity(WorkLinkEntity workLinkEntity)
        {
            SQLBuilder sqlBuilder = new SQLBuilder(DBProvider);
            sqlBuilder.BeginUpdate(this.CurrentTableName);
            this.SetEntity(sqlBuilder, workLinkEntity);
            sqlBuilder.SetWhere(WorkLinkTable.FieldWorkLinkId, workLinkEntity.WorkLinkId);
            return sqlBuilder.EndUpdate();
        }

        /// <summary>
        /// 设置实体
        /// </summary>
        /// <param name="sqlBuilder">Sql语句生成器</param>
        /// <param name="workLinkEntity">实体</param>
        private void SetEntity(SQLBuilder sqlBuilder, WorkLinkEntity workLinkEntity)
        {
            sqlBuilder.SetValue(WorkLinkTable.FieldWorkFlowId, workLinkEntity.WorkFlowId);
            sqlBuilder.SetValue(WorkLinkTable.FieldStartTaskId, workLinkEntity.StartTaskId);
            sqlBuilder.SetValue(WorkLinkTable.FieldEndTaskId, workLinkEntity.EndTaskId);
            if (DBProvider.CurrentDbType == CurrentDbType.MySql)
            {
                sqlBuilder.SetValue("`" + WorkLinkTable.FieldCondition + "`", workLinkEntity.Condition); //mySql中的"Condition"为保留字，会报错，加键盘上1左边的`括起来即可
            }
            else
            {
                sqlBuilder.SetValue(WorkLinkTable.FieldCondition, workLinkEntity.Condition);
            }

            sqlBuilder.SetValue(WorkLinkTable.FieldDescription, workLinkEntity.Description);
            sqlBuilder.SetValue(WorkLinkTable.FieldBreakX, workLinkEntity.BreakX);
            sqlBuilder.SetValue(WorkLinkTable.FieldBreakY, workLinkEntity.BreakY);
            sqlBuilder.SetValue(WorkLinkTable.FieldCommandName, workLinkEntity.CommandName);
            sqlBuilder.SetValue(WorkLinkTable.FieldPriority, workLinkEntity.Priority);
        }

        /// <summary>
        /// 删除实体
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>影响行数</returns>
        public int Delete(string id)
        {
            return this.Delete(new KeyValuePair<string, object>(WorkLinkTable.FieldWorkLinkId, id));
        }
    }
}
