#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
     using RDIFramework.Utilities;

    /// <summary>
    /// CiItemsEntity
    /// 数据字典主表
    ///
    /// 修改纪录
    ///
    ///     2014-07-30 版本: 2.8 EricHu 以自动属性进行重新组织。
    ///		2012-03-02 版本：1.0 EricHu 创建主键。
    ///
    /// 版本：3.0
    ///
    /// <author>
    ///		<name>EricHu</name>
    ///		<date>2012-03-02</date>
    /// </author>
    /// </summary>
    public partial class CiItemsEntity : BaseEntity
    {
        /// <summary>
        /// 主键
        /// </summary>		
        public string Id { get; set; }

        /// <summary>
        /// 父节点主键
        /// </summary>
        public String ParentId { get; set; }

        /// <summary>
        /// 编号
        /// </summary>		
        public string Code { get; set; }

        /// <summary>
        /// 名称
        /// </summary>		
        public string FullName { get; set; }

        /// <summary>
        /// 数据字典分类
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        /// 目标存储表
        /// </summary>		
        public string TargetTable { get; set; }

        /// <summary>
        /// 树型结构
        /// </summary>		
        public int? IsTree { get; set; }

        /// <summary>
        /// 编号字段对应值
        /// </summary>		
        public string UseItemCode { get; set; }

        /// <summary>
        /// 名称字段对应值
        /// </summary>		
        public string UseItemName { get; set; }

        /// <summary>
        /// 值字段对应值
        /// </summary>		
        public string UseItemValue { get; set; }

        /// <summary>
        /// 允许编辑
        /// </summary>		
        public int? AllowEdit { get; set; }

        /// <summary>
        /// 允许删除
        /// </summary>		
        public int? AllowDelete { get; set; }

        /// <summary>
        /// 删除标记
        /// </summary>		
        public int? DeleteMark { get; set; }

        /// <summary>
        /// 描述
        /// </summary>		
        public string Description { get; set; }

        /// <summary>
        /// 有效
        /// </summary>		
        public int? Enabled { get; set; }

        /// <summary>
        /// 排序码
        /// </summary>		
        public int? SortCode { get; set; }

        /// <summary>
        /// 创建日期
        /// </summary>		
        public DateTime? CreateOn { get; set; }

        /// <summary>
        /// 创建用户主键
        /// </summary>		
        public string CreateUserId { get; set; }

        /// <summary>
        /// 创建用户
        /// </summary>		
        public string CreateBy { get; set; }

        /// <summary>
        /// 修改日期
        /// </summary>		
        public DateTime? ModifiedOn { get; set; }

        /// <summary>
        /// 修改用户主键
        /// </summary>		
        public string ModifiedUserId { get; set; }

        /// <summary>
        /// 修改用户
        /// </summary>		
        public string ModifiedBy { get; set; }

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CiItemsEntity()
        {
            AllowEdit = 1;
            AllowDelete = 1;
            Enabled = 0;
            SortCode = null;
            this.DeleteMark = 0;
            this.IsTree = 0;
            CreateOn = DateTime.Now;
        }

        /// <summary>
        /// 从数据行读取
        /// </summary>
        /// <param name="dataRow">数据行</param>
        protected override BaseEntity GetFrom(IDataRow dataRow)
        {
            this.Id = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldId]);
            this.ParentId = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldParentId]);
            this.Code = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldCode]);
            this.FullName = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldFullName]);
            this.Category = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldCategory]);
            this.TargetTable = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldTargetTable]);
            this.IsTree = BusinessLogic.ConvertToNullableInt(dataRow[CiItemsTable.FieldIsTree]);
            this.UseItemCode = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldUseItemCode]);
            this.UseItemName = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldUseItemName]);
            this.UseItemValue = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldUseItemValue]);
            this.AllowEdit = BusinessLogic.ConvertToNullableInt(dataRow[CiItemsTable.FieldAllowEdit]);
            this.AllowDelete = BusinessLogic.ConvertToNullableInt(dataRow[CiItemsTable.FieldAllowDelete]);
            this.DeleteMark = BusinessLogic.ConvertToNullableInt(dataRow[CiItemsTable.FieldDeleteMark]);
            this.Description = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldDescription]);
            this.Enabled = BusinessLogic.ConvertToNullableInt(dataRow[CiItemsTable.FieldEnabled]);
            this.SortCode = BusinessLogic.ConvertToNullableInt(dataRow[CiItemsTable.FieldSortCode]);
            this.CreateOn = BusinessLogic.ConvertToNullableDateTime(dataRow[CiItemsTable.FieldCreateOn]);
            this.CreateUserId = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldCreateUserId]);
            this.CreateBy = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldCreateBy]);
            this.ModifiedOn = BusinessLogic.ConvertToNullableDateTime(dataRow[CiItemsTable.FieldModifiedOn]);
            this.ModifiedUserId = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldModifiedUserId]);
            this.ModifiedBy = BusinessLogic.ConvertToString(dataRow[CiItemsTable.FieldModifiedBy]);
            return this;
        }
    }
}
