#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 框架官网：http://www.rdiframework.net/
// 框架博客：http://blog.rdiframework.net/
//    Email：406590790@qq.com
//       QQ：406590790
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion


using System;

namespace CRM.BizLogic
{
    /// <summary>
    /// CUSTOMERCHANCETable
    /// 客户机会
    /// 
    /// 修改纪录
    /// 
    /// 2013-07-11 版本：1.0 XuWangBin 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>XuWangBin</name>
    /// <date>2013-07-11</date>
    /// </author>
    /// </summary>
    public partial class CUSTOMERCHANCETable
    {
        ///<summary>
        /// 客户机会
        ///</summary>
        [NonSerialized]
        public static string TableName = "CUSTOMER_CHANCE";

        ///<summary>
        /// 主键
        ///</summary>
        [NonSerialized]
        public static string FieldId = "Id";

        ///<summary>
        /// 客户信息_主键
        ///</summary>
        [NonSerialized]
        public static string FieldCUSTOMERID = "CUSTOMERID";

        ///<summary>
        /// 客户名称
        ///</summary>
        [NonSerialized]
        public static string FieldCUSTOMERNAME = "CUSTOMERNAME";

        ///<summary>
        /// 主题
        ///</summary>
        [NonSerialized]
        public static string FieldTHEME = "THEME";

        ///<summary>
        /// 负责人
        ///</summary>
        [NonSerialized]
        public static string FieldFZR = "FZR";

        ///<summary>
        /// 状态
        ///</summary>
        [NonSerialized]
        public static string FieldSTATE = "STATE";

        ///<summary>
        /// 阶段
        ///</summary>
        [NonSerialized]
        public static string FieldMOMENT = "MOMENT";

        ///<summary>
        /// 来源
        ///</summary>
        [NonSerialized]
        public static string FieldSOURCE = "SOURCE";

        ///<summary>
        /// 预计金额
        ///</summary>
        [NonSerialized]
        public static string FieldINTENDPRICE = "INTENDPRICE";

        ///<summary>
        /// 可能性
        ///</summary>
        [NonSerialized]
        public static string FieldPOSSIBILITY = "POSSIBILITY";

        ///<summary>
        /// 开始时间
        ///</summary>
        [NonSerialized]
        public static string FieldSTARTDATE = "STARTDATE";

        ///<summary>
        /// 结束时间
        ///</summary>
        [NonSerialized]
        public static string FieldENDDATE = "ENDDATE";

        ///<summary>
        /// 实际结束时间
        ///</summary>
        [NonSerialized]
        public static string FieldREALENDDATE = "REALENDDATE";

        ///<summary>
        /// 备注
        ///</summary>
        [NonSerialized]
        public static string FieldDESCRIPTION = "DESCRIPTION";

        ///<summary>
        /// 排序码
        ///</summary>
        [NonSerialized]
        public static string FieldSORTCODE = "SORTCODE";

        ///<summary>
        /// 删除标志
        ///</summary>
        [NonSerialized]
        public static string FieldDELETEMARK = "DELETEMARK";

        ///<summary>
        /// 有效标志
        ///</summary>
        [NonSerialized]
        public static string FieldENABLE = "ENABLE";

        ///<summary>
        /// 创建日期
        ///</summary>
        [NonSerialized]
        public static string FieldCreateOn = "CreateOn";

        ///<summary>
        /// 创建用户主键
        ///</summary>
        [NonSerialized]
        public static string FieldCreateUserId = "CreateUserId";

        ///<summary>
        /// 创建用户
        ///</summary>
        [NonSerialized]
        public static string FieldCREATEUSER = "CREATEUSER";

        ///<summary>
        /// 修改日期
        ///</summary>
        [NonSerialized]
        public static string FieldMODIFYON = "MODIFYON";

        ///<summary>
        /// 修改用户主键
        ///</summary>
        [NonSerialized]
        public static string FieldMODIFIEDUSERID = "MODIFIEDUSERID";

        ///<summary>
        /// 修改用户
        ///</summary>
        [NonSerialized]
        public static string FieldMODIFYUSER = "MODIFYUSER";
    }
}