#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System.Data;
using System.Collections.Generic;
using System.Reflection;
using System.ServiceModel;

namespace RDIFramework.BizLogic
{
	using RDIFramework.Utilities;

	/// <summary>
	/// QueryEngineService
	/// 查询引擎主表服务层
	/// 
	/// 修改记录
	/// 
	///	2015-09-18 版本：1.0 EricHu 建立查询引擎服务层。
	///		
	/// 版本：1.0
	///
	/// <author>
	///	<name>EricHu</name>
	///	<date>2015-09-18</date>
	/// </author> 
	/// </summary>
	[ServiceBehavior(IncludeExceptionDetailInFaults = true)]
	public partial class QueryEngineService : System.MarshalByRefObject, IQueryEngineService
	{
        private string serviceName = RDIFrameworkMessage.QueryEnginService;

        #region public string AddQueryEngine(UserInfo userInfo, QueryEngineEntity entity, out string statusCode, out string statusMessage) 新增查询引擎主表
        /// <summary>
		/// 新增查询引擎主表
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="entity">查询引擎主表实体</param>
		/// <param name="statusCode">返回状态码</param>
		/// <param name="statusMessage">返回状态消息</param>
		/// <returns>主鍵</returns>
        public string AddQueryEngine(UserInfo userInfo, QueryEngineEntity entity, out string statusCode, out string statusMessage)
		{
            var returnValue = string.Empty;
            string returnCode = string.Empty;
            string returnMessage = string.Empty;
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_Add);

            ServiceUtil.ProcessRDIWriteDb(userInfo, parameter, dbProvider =>
            {
                var manager = new QueryEngineManager(dbProvider, userInfo);
                returnValue = manager.Add(entity, out returnCode);
                returnMessage = manager.GetStateMessage(returnCode);
            });
            statusCode = returnCode;
            statusMessage = returnMessage;
            return returnValue;
		}
		#endregion

        #region public int UpdateQueryEngine(UserInfo userInfo, QueryEngineEntity entity, out string statusCode, out string statusMessage) 更新查询引擎主表
        /// <summary>
		/// 更新查询引擎主表
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="entity">查询引擎主表实体</param>
		/// <param name="statusCode">返回状态码</param>
		/// <param name="statusMessage">返回状态信息</param>
		/// <returns>影响行数</returns>
        public int UpdateQueryEngine(UserInfo userInfo, QueryEngineEntity entity, out string statusCode, out string statusMessage)
		{
            int returnValue = 0;
            string returnCode = string.Empty;
            string returnMessage = string.Empty;
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_Update);

            ServiceUtil.ProcessRDIWriteDb(userInfo, parameter, dbProvider =>
            {
                var manager = new QueryEngineManager(dbProvider, userInfo);
                returnValue = manager.UpdateEntity(entity, out returnCode);
                returnMessage = manager.GetStateMessage(returnCode);
            });
            statusCode = returnCode;
            statusMessage = returnMessage;
            return returnValue;
		}
		#endregion

        #region public DataTable GetQueryEngineDT(UserInfo userInfo) 获取查询引擎主表列表
        /// <summary>
		/// 获取查询引擎主表列表
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <returns>数据表</returns>
        public DataTable GetQueryEngineDT(UserInfo userInfo)
		{
            var dataTable = new DataTable(QueryEngineTable.TableName);
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_GetDT);
            
            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                dataTable = new QueryEngineManager(dbProvider, userInfo).GetDT(QueryEngineTable.FieldDeleteMark, 0, QueryEngineTable.FieldSortCode);
                dataTable.TableName = QueryEngineTable.TableName;
            });
            return dataTable;
		}
		#endregion

        #region public DataTable GetQueryEngineDTByPage(UserInfo userInfo, string searchValue, out int recordCount, int pageIndex = 1, int pageSize = 20, string sortExpression = null) 分页获取查询引擎主表列表
        /// <summary>
		/// 分页获取查询引擎主表列表
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="searchValue">查询关键字</param>
		/// <param name="recordCount">记录数</param>
		/// <param name="pageIndex">当前页</param>
		/// <param name="pageSize">每页显示记录条数</param>
		/// <param name="sortExpression">排序字段</param>
		/// <returns>数据表</returns>
        public DataTable GetQueryEngineDTByPage(UserInfo userInfo, string searchValue, out int recordCount, int pageIndex = 1, int pageSize = 20, string sortExpression = null)
		{
            var dataTable = new DataTable(QueryEngineTable.TableName);
            var returnRecordCount = 0;
            var parameter = ParameterUtil.CreateWithOutMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName);

            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                var manager = new QueryEngineManager(dbProvider, userInfo);
                if (string.IsNullOrEmpty(searchValue))
                {
                    searchValue = QueryEngineTable.FieldDeleteMark + " = 0 ";
                }
                else
                {
                    searchValue += " AND " + QueryEngineTable.FieldDeleteMark + " = 0 ";
                }

                dataTable = manager.GetDTByPage(out returnRecordCount, pageIndex, pageSize, searchValue, sortExpression);
                dataTable.TableName = QueryEngineTable.TableName;
            });
            recordCount = returnRecordCount;
            return dataTable;
		}
		#endregion

        #region public QueryEngineEntity GetQueryEngineEntity(UserInfo userInfo, string id) 获取查询引擎主表实体
        /// <summary>
		/// 得到查询引擎主表实体
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="id">主鍵</param>
		/// <returns>实体</returns>
        public QueryEngineEntity GetQueryEngineEntity(UserInfo userInfo, string id)
		{
            QueryEngineEntity entity = null;
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_GetEntity);

            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                entity = new QueryEngineManager(dbProvider, userInfo).GetEntity(id);
            });
            return entity;
		}
		#endregion

        #region public DataTable GetQueryEngineDTByIds(UserInfo userInfo, string[] ids) 根据主键数组获取数据
        /// <summary>
		/// 根据主键数组获取数据
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="ids">主鍵</param>
		/// <returns>数据表</returns>
        public DataTable GetQueryEngineDTByIds(UserInfo userInfo, string[] ids)
		{
            var dataTable = new DataTable(QueryEngineTable.TableName);
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_GetDTByIds);

            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                dataTable = new QueryEngineManager(dbProvider, userInfo).GetDT(QueryEngineTable.FieldId, ids, QueryEngineTable.FieldSortCode);
                dataTable.TableName = QueryEngineTable.TableName;
            });
		    return dataTable;
		}
		#endregion

        #region public DataTable GetQueryEngineDTByValues(UserInfo userInfo, List<KeyValuePair<string, object>> parameters) 根据条件获取数据
        /// <summary>
		/// 根据条件获取数据
		/// </summary>
		/// <param name="userInfo">用户</param>
        /// <param name="parameters">参数</param>
		/// <returns>数据表</returns>
        public DataTable GetQueryEngineDTByValues(UserInfo userInfo, List<KeyValuePair<string, object>> parameters)
		{
            var dataTable = new DataTable(QueryEngineTable.TableName);
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_GetDTByValues);

            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                dataTable = new QueryEngineManager(dbProvider, userInfo).GetDT(parameters);
                dataTable.TableName = QueryEngineTable.TableName;
            });
            return dataTable;
		}
		#endregion

        #region public DataTable GetQueryEngineDTByParent(UserInfo userInfo, string parentId) 按父节点获取列表
        /// <summary> 
        /// 按父节点获取列表
        /// </summary>
        /// <param name="userInfo">用户</param>
        /// <param name="parentId">父节点主键</param>
        /// <returns>数据表</returns>
        public DataTable GetQueryEngineDTByParent(UserInfo userInfo, string parentId)
        {
            var dataTable = new DataTable(QueryEngineTable.TableName);
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_GetDTByParent);

            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                dataTable = new QueryEngineManager(dbProvider, userInfo).GetDT(QueryEngineTable.FieldParentId, parentId, QueryEngineTable.FieldDeleteMark, 0, QueryEngineTable.FieldSortCode);
                dataTable.TableName = QueryEngineTable.TableName;
            });
            return dataTable;
        }
        #endregion

        #region public int DeleteQueryEngine(UserInfo userInfo, string id) 删除指定数据
        /// <summary>
		/// 删除指定数据
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="id">主鍵</param>
		/// <returns>数据表</returns>
        public int DeleteQueryEngine(UserInfo userInfo, string id)
		{
            var returnValue = 0;
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_Delete, "主键：" + id);

            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                returnValue = new QueryEngineManager(dbProvider, userInfo).Delete(id);
            });

            return returnValue;
		}
		#endregion

        #region public int BatchDeleteQueryEngine(UserInfo userInfo, string[] ids) 批量删除数据
        /// <summary>
		/// 批量删除数据
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="ids">主键数组</param>
		/// <returns>影响行数</returns>
        public int BatchDeleteQueryEngine(UserInfo userInfo, string[] ids)
		{
            var returnValue = 0;
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_BatchDelete);

            ServiceUtil.ProcessRDIWriteDbWithTran(userInfo, parameter, dbProvider =>
            {
                returnValue = new QueryEngineManager(dbProvider, userInfo).BatchDelete(ids);
            });
            return returnValue;
		}
		#endregion

        #region public int SetDeletedQueryEngine(UserInfo userInfo, string[] ids) 批量设置删除标志
        /// <summary>
		/// 批量设置删除标志
		/// </summary>
		/// <param name="userInfo">用户</param>
		/// <param name="ids">主键数组</param>
		/// <returns>影响行数</returns>
        public int SetDeletedQueryEngine(UserInfo userInfo, string[] ids)
		{
            var returnValue = 0;
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_SetDeleted);

            ServiceUtil.ProcessRDIWriteDbWithTran(userInfo, parameter, dbProvider =>
            {
                returnValue = new QueryEngineManager(dbProvider, userInfo).SetDeleted(ids);
            });

            return returnValue;
		}
		#endregion

        #region public int MoveToQueryEngine(UserInfo userInfo, string id, string parentId) 移动数据
        /// <summary>
        /// 移动实体
        /// </summary>
        /// <param name="userInfo">用户</param>
        /// <param name="id">主键</param>
        /// <param name="parentId">父主键</param>
        /// <returns>影响行数</returns>
        public int MoveToQueryEngine(UserInfo userInfo, string id, string parentId)
        {
            var returnValue = 0;
            var parameter = ParameterUtil.CreateWithMessage(userInfo, MethodBase.GetCurrentMethod(), this.serviceName, RDIFrameworkMessage.QueryEnginService_MoveTo, "权限项主键：" + id + ",父主键:" + parentId);

            ServiceUtil.ProcessRDIReadDb(userInfo, parameter, dbProvider =>
            {
                returnValue = new QueryEngineManager(dbProvider, userInfo).MoveTo(id, parentId);
            });
            return returnValue;
        }
        #endregion
	}
}
