#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
    /// <summary>
    /// QueryEngineDefineTable
    /// 查询引擎定义
    /// 
    /// 修改纪录
    /// 
    /// 2015-09-18 版本：1.0 EricHu 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>EricHu</name>
    /// <date>2015-09-18</date>
    /// </author>
    /// </summary>
    public partial class QueryEngineDefineTable
    {
        ///<summary>
        /// 查询引擎定义
        ///</summary>
        [NonSerialized]
        public static string TableName = "QUERYENGINEDEFINE";

        ///<summary>
        /// 主键
        ///</summary>
        [NonSerialized]
        public static string FieldId = "ID";

        ///<summary>
        /// 查询引擎主键
        ///</summary>
        [NonSerialized]
        public static string FieldQueryEngineId = "QUERYENGINEID";

        ///<summary>
        /// 编号
        ///</summary>
        [NonSerialized]
        public static string FieldCode = "CODE";

        ///<summary>
        /// 名称
        ///</summary>
        [NonSerialized]
        public static string FieldFullName = "FULLNAME";

        ///<summary>
        /// 数据库连接名称
        ///</summary>
        [NonSerialized]
        public static string FieldDataBaseLinkName = "DATABASELINKNAME";

        ///<summary>
        /// 取值：
        ///    1、表或视图(默认)
        ///    2、存储过程
        ///</summary>
        [NonSerialized]
        public static string FieldDataSourceType = "DATASOURCETYPE";

        ///<summary>
        /// 数据源名称
        ///</summary>
        [NonSerialized]
        public static string FieldDataSourceName = "DATASOURCENAME";

        ///<summary>
        /// 查询语句主键
        ///</summary>
        [NonSerialized]
        public static string FieldQueryStringKey = "QUERYSTRINGKEY";

        ///<summary>
        /// Select字段
        ///</summary>
        [NonSerialized]
        public static string FieldSelectedField = "SELECTEDFIELD";

        ///<summary>
        /// OrderBy字段
        ///</summary>
        [NonSerialized]
        public static string FieldOrderByField = "ORDERBYFIELD";

        ///<summary>
        /// 查询语句
        ///</summary>
        [NonSerialized]
        public static string FieldQueryString = "QUERYSTRING";

        ///<summary>
        /// 允许编辑
        ///</summary>
        [NonSerialized]
        public static string FieldAllowEdit = "ALLOWEDIT";

        ///<summary>
        /// 允许删除
        ///</summary>
        [NonSerialized]
        public static string FieldAllowDelete = "ALLOWDELETE";

        ///<summary>
        /// 删除标记
        ///</summary>
        [NonSerialized]
        public static string FieldDeleteMark = "DELETEMARK";

        ///<summary>
        /// 描述
        ///</summary>
        [NonSerialized]
        public static string FieldDescription = "DESCRIPTION";

        ///<summary>
        /// 有效
        ///</summary>
        [NonSerialized]
        public static string FieldEnabled = "ENABLED";

        ///<summary>
        /// 排序码
        ///</summary>
        [NonSerialized]
        public static string FieldSortCode = "SORTCODE";

        ///<summary>
        /// 创建日期
        ///</summary>
        [NonSerialized]
        public static string FieldCreateOn = "CREATEON";

        ///<summary>
        /// 创建用户主键
        ///</summary>
        [NonSerialized]
        public static string FieldCreateUserId = "CREATEUSERID";

        ///<summary>
        /// 创建用户
        ///</summary>
        [NonSerialized]
        public static string FieldCreateBy = "CREATEBY";

        ///<summary>
        /// 修改日期
        ///</summary>
        [NonSerialized]
        public static string FieldModifiedOn = "MODIFIEDON";

        ///<summary>
        /// 修改用户主键
        ///</summary>
        [NonSerialized]
        public static string FieldModifiedUserId = "MODIFIEDUSERID";

        ///<summary>
        /// 修改用户
        ///</summary>
        [NonSerialized]
        public static string FieldModifiedBy = "MODIFIEDBY";
    }
}
