#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
    /// <summary>
    /// WorkTaskTable
    /// 流程任务
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 EricHu 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>EricHu</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class WorkTaskTable
    {
        ///<summary>
        /// 表名称
        ///</summary>
        [NonSerialized]
        public static string TableName = "WORKTASK";

        ///<summary>
        /// 任务主键
        ///</summary>
        [NonSerialized]
        public static string FieldWorkTaskId = "WORKTASKID";

        ///<summary>
        /// 工作流程主键
        ///</summary>
        [NonSerialized]
        public static string FieldWorkFlowId = "WORKFLOWID";

        ///<summary>
        /// 任务类型：
        /// 1：启动节点、 2：终止节点、3：交互节点、4：控制节点、5：查看节点、6：子流程节点、        
        ///</summary>
        [NonSerialized]
        public static string FieldTaskTypeId = "TASKTYPEID";

        ///<summary>
        /// and ,or表示与或节点
        ///</summary>
        [NonSerialized]
        public static string FieldTaskTypeAndOr = "TASKTYPEANDOR";

        ///<summary>
        /// 同一流程任务名称唯一
        ///</summary>
        [NonSerialized]
        public static string FieldTaskCaption = "TASKCAPTION";

        ///<summary>
        /// X坐标
        ///</summary>
        [NonSerialized]
        public static string FieldIXPosition = "IXPOSITION";

        ///<summary>
        /// Y坐标
        ///</summary>
        [NonSerialized]
        public static string FieldIYPosition = "IYPOSITION";

        ///<summary>
        /// 描述
        ///</summary>
        [NonSerialized]
        public static string FieldDescription = "DESCRIPTION";

        ///<summary>
        /// 命令分支
        ///</summary>
        [NonSerialized]
        public static string FieldCommands = "COMMANDS";

        ///<summary>
        /// 处理者策略：1：所有用户共享任务、2：所有用户处理任务   
        ///</summary>
        [NonSerialized]
        public static string FieldOperRule = "OPERRULE";

        ///<summary>
        /// 处理人是提交人时是否跳过本处理
        ///</summary>
        [NonSerialized]
        public static string FieldIsJumpSelf = "ISJUMPSELF";
    }
}
