#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
    /// <summary>
    /// WorkFlowEventTable
    /// 
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 XuWangBin 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>XuWangBin</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class WorkFlowEventTable
    {
        ///<summary>
        /// 表名称
        ///</summary>
        [NonSerialized]
        public static string TableName = "WORKFLOWEVENT";

        ///<summary>
        /// Guid
        ///</summary>
        [NonSerialized]
        public static string FieldGuid = "GUID";

        ///<summary>
        /// 流程模版ID
        ///</summary>
        [NonSerialized]
        public static string FieldWorkFlowId = "WORKFLOWID";

        ///<summary>
        /// 任务模版ID
        ///</summary>
        [NonSerialized]
        public static string FieldWorkTaskId = "WORKTASKID";

        ///<summary>
        /// 子流程Id
        ///</summary>
        [NonSerialized]
        public static string FieldRemark = "REMARK";

        ///<summary>
        /// 任务超时，短消息提醒。
        ///</summary>
        [NonSerialized]
        public static string FieldOtSms = "OTSMS";

        ///<summary>
        /// 超时，及时消息提醒，需要及时消息软件配合（例如:QQ,msn...）
        ///</summary>
        [NonSerialized]
        public static string FieldOtMsg = "OTMSG";

        ///<summary>
        /// 任务超时，邮件提醒。
        ///</summary>
        [NonSerialized]
        public static string FieldOtEmail = "OTEMAIL";

        ///<summary>
        /// 任务到达，短信提醒。
        ///</summary>
        [NonSerialized]
        public static string FieldRmSms = "RMSMS";

        ///<summary>
        /// 任务到达及时消息提醒
        ///</summary>
        [NonSerialized]
        public static string FieldRmMsg = "RMMSG";

        ///<summary>
        /// 任务到达邮件提醒
        ///</summary>
        [NonSerialized]
        public static string FieldRmEmail = "RMEMAIL";

        ///<summary>
        /// 任务超时同时提交给某人
        ///</summary>
        [NonSerialized]
        public static string FieldOtToUsers = "OTTOUSERS";

        ///<summary>
        /// 任务到达同时提交给某人
        ///</summary>
        [NonSerialized]
        public static string FieldRmToUsers = "RMTOUSERS";
    }
}
