#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
    /// <summary>
    /// WorkOutTimeTable
    /// 
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 XuWangBin 创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name>XuWangBin</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    public partial class WorkOutTimeTable
    {
        ///<summary>
        /// 表名称
        ///</summary>
        [NonSerialized]
        public static string TableName = "WORKOUTTIME";

        ///<summary>
        /// Guid
        ///</summary>
        [NonSerialized]
        public static string FieldGuid = "GUID";

        ///<summary>
        /// 流程模版ID
        ///</summary>
        [NonSerialized]
        public static string FieldWorkFlowId = "WORKFLOWID";

        ///<summary>
        /// 任务模版ID
        ///</summary>
        [NonSerialized]
        public static string FieldWorkTaskId = "WORKTASKID";

        ///<summary>
        /// 保留未用
        ///</summary>
        [NonSerialized]
        public static string FieldName = "NAME";

        ///<summary>
        /// 普通-天
        ///</summary>
        [NonSerialized]
        public static string FieldDays = "DAYS";

        ///<summary>
        /// 普通-时
        ///</summary>
        [NonSerialized]
        public static string FieldHours = "HOURS";

        ///<summary>
        /// 普通-分
        ///</summary>
        [NonSerialized]
        public static string FieldMinutes = "MINUTES";

        ///<summary>
        /// 紧急-天
        ///</summary>
        [NonSerialized]
        public static string FieldDays1 = "DAYS1";

        ///<summary>
        /// 紧急-时
        ///</summary>
        [NonSerialized]
        public static string FieldHours1 = "HOURS1";

        ///<summary>
        /// 紧急-分
        ///</summary>
        [NonSerialized]
        public static string FieldMinutes1 = "MINUTES1";

        ///<summary>
        /// 特急-天
        ///</summary>
        [NonSerialized]
        public static string FieldDays2 = "DAYS2";

        ///<summary>
        /// 特急-时
        ///</summary>
        [NonSerialized]
        public static string FieldHours2 = "HOURS2";

        ///<summary>
        /// 特急-分
        ///</summary>
        [NonSerialized]
        public static string FieldMinutes2 = "MINUTES2";

        ///<summary>
        /// 是否处理
        ///</summary>
        [NonSerialized]
        public static string FieldDone = "DONE";

        ///<summary>
        /// 超时多久
        ///</summary>
        [NonSerialized]
        public static string FieldOverTime = "OVERTIME";
    }
}
