#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
    using RDIFramework.Utilities;

    /// <summary>
    /// WorkTaskEntity
    /// 流程任务
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 XuWangBin 创建主键。
    /// 
    /// 版本：3.0
    /// 
    /// <author>
    /// <name>XuWangBin</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    [Serializable]
    public partial class WorkTaskEntity : BaseEntity
    {
        /// <summary>
        /// 任务主键
        /// </summary>
        public String WorkTaskId { get; set; }

        /// <summary>
        /// 工作流程主键
        /// </summary>
        public String WorkFlowId { get; set; }

        /// <summary>
        /// 任务类型：
        /// 1启动节点
        /// 2终止节点
        /// 3交互节点
        /// 4控制节点
        /// 5查看节点
        /// 6子流程节点
        /// </summary>
        public String TaskTypeId { get; set; }

        /// <summary>
        /// and ,or表示与或节点
        /// </summary>
        public String TaskTypeAndOr { get; set; }

        /// <summary>
        /// 同一流程任务名称唯一
        /// </summary>
        public String TaskCaption { get; set; }

        /// <summary>
        /// X坐标
        /// </summary>
        public int? IXPosition { get; set; }

        /// <summary>
        /// Y坐标
        /// </summary>
        public int? IYPosition { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public String Description { get; set; }

        /// <summary>
        /// 命令分支
        /// </summary>
        public String Commands { get; set; }

        /// <summary>
        /// 处理者策略：
        /// 1所有用户共享任务
        /// 2所有用户处理任务   
        /// </summary>
        public String OperRule { get; set; }

        /// <summary>
        /// 处理人是提交人时是否跳过本处理
        /// </summary>
        public int? IsJumpSelf { get; set; }

        /// <summary>
        /// 构造函数
        /// </summary>
        public WorkTaskEntity()
        {
            this.IXPosition = null;
            this.IYPosition = null;
            this.TaskTypeAndOr = "and";
            this.Commands = "提交";
        }

        /// <summary>
        /// 从数据行读取
        /// </summary>
        /// <param name="dataRow">数据行</param>
        protected override BaseEntity GetFrom(IDataRow dataRow)
        {
            this.WorkTaskId = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldWorkTaskId]);
            this.WorkFlowId = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldWorkFlowId]);
            this.TaskTypeId = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldTaskTypeId]);
            this.TaskTypeAndOr = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldTaskTypeAndOr]);
            this.TaskCaption = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldTaskCaption]);
            this.IXPosition = BusinessLogic.ConvertToNullableInt(dataRow[WorkTaskTable.FieldIXPosition]);
            this.IYPosition = BusinessLogic.ConvertToNullableInt(dataRow[WorkTaskTable.FieldIYPosition]);
            this.Description = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldDescription]);
            this.Commands = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldCommands]);
            this.OperRule = BusinessLogic.ConvertToString(dataRow[WorkTaskTable.FieldOperRule]);
            this.IsJumpSelf = BusinessLogic.ConvertToNullableInt(dataRow[WorkTaskTable.FieldIsJumpSelf]);
            return this;
        }
    }
}
