#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
    using RDIFramework.Utilities;

    /// <summary>
    /// WorkLinkEntity
    /// 流程连线配置
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 XuWangBin 创建主键。
    /// 
    /// 版本：3.0
    /// 
    /// <author>
    /// <name>XuWangBin</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    [Serializable]
    public partial class WorkLinkEntity : BaseEntity
    {
        /// <summary>
        /// 工作流连接配置主键
        /// </summary>
        public String WorkLinkId { get; set; }

        /// <summary>
        /// 所属流程模版主键
        /// </summary>
        public String WorkFlowId { get; set; }

        /// <summary>
        /// 连接的起点
        /// </summary>
        public String StartTaskId { get; set; }

        /// <summary>
        /// 连线的终点
        /// </summary>
        public String EndTaskId { get; set; }

        /// <summary>
        /// 记录走此支路所需要的表达式条件
        /// </summary>
        /// <example>
        /// <%VarGuid%>==’5’
        /// </example>
        public String Condition { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public String Description { get; set; }

        /// <summary>
        /// 折点X坐标，多个折点间逗号分隔
        /// </summary>
        public String BreakX { get; set; }

        /// <summary>
        /// 折点Y坐标，多个折点间逗号分隔
        /// </summary>
        public String BreakY { get; set; }

        /// <summary>
        /// 关联命令名称
        /// </summary>
        public String CommandName { get; set; }

        /// <summary>
        /// 命令级别，默认值 0(最高)
        /// </summary>
        public int? Priority { get; set; }

        /// <summary>
        /// 构造函数
        /// </summary>
        public WorkLinkEntity()
        {
            this.CommandName = "提交";
        }

        /// <summary>
        /// 从数据行读取
        /// </summary>
        /// <param name="dataRow">数据行</param>
        protected override BaseEntity GetFrom(IDataRow dataRow)
        {
            this.WorkLinkId = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldWorkLinkId]);
            this.WorkFlowId = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldWorkFlowId]);
            this.StartTaskId = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldStartTaskId]);
            this.EndTaskId = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldEndTaskId]);
            this.Condition = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldCondition]);
            this.Description = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldDescription]);
            this.BreakX = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldBreakX]);
            this.BreakY = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldBreakY]);
            this.CommandName = BusinessLogic.ConvertToString(dataRow[WorkLinkTable.FieldCommandName]);
            this.Priority = BusinessLogic.ConvertToNullableInt(dataRow[WorkLinkTable.FieldPriority]);
            return this;
        }
    }
}
