#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//     RDIFramework.NET（.NET快速信息化系统开发、整合框架）是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//     RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
//	框架官网：http://www.rdiframework.net/
//	框架博客：http://blog.rdiframework.net/
//	交流QQ：406590790 
//	邮件交流：406590790@qq.com
//	其他博客：
//    http://www.cnblogs.com/huyong 
//    http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由RDIFramework.NET平台代码生成工具自动生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;

namespace RDIFramework.BizLogic
{
    using RDIFramework.Utilities;

    /// <summary>
    /// WorkOutTimeEntity
    /// 工作任务超时设置
    /// 
    /// 修改纪录
    /// 
    /// 2014-06-03 版本：1.0 EricHu 创建主键。
    /// 
    /// 版本：3.0
    /// 
    /// <author>
    /// <name>EricHu</name>
    /// <date>2014-06-03</date>
    /// </author>
    /// </summary>
    [Serializable]
    public partial class WorkOutTimeEntity : BaseEntity
    {
        /// <summary>
        /// Guid
        /// </summary>
        public String Guid { get; set; }

        /// <summary>
        /// 流程模版ID
        /// </summary>
        public String WorkFlowId { get; set; }

        /// <summary>
        /// 任务模版ID
        /// </summary>
        public String WorkTaskId { get; set; }

        /// <summary>
        /// 保留未用
        /// </summary>
        public String Name { get; set; }
       
        /// <summary>
        /// 普通-天
        /// </summary>
        public int? Days { get; set; }

        /// <summary>
        /// 普通-时
        /// </summary>
        public int? Hours { get; set; }

        /// <summary>
        /// 普通-分
        /// </summary>
        public int? Minutes { get; set; }

        /// <summary>
        /// 紧急-天
        /// </summary>
        public int? Days1 { get; set; }

        /// <summary>
        /// 紧急-时
        /// </summary>
        public int? Hours1 { get; set; }

        /// <summary>
        /// 紧急-分
        /// </summary>
        public int? Minutes1 { get; set; }

        /// <summary>
        /// 特急-天
        /// </summary>
        public int? Days2 { get; set; }

        /// <summary>
        /// 特急-时
        /// </summary>
        public int? Hours2 { get; set; }

        /// <summary>
        /// 特急-分
        /// </summary>
        public int? Minutes2 { get; set; }


        /// <summary>
        /// 是否处理
        /// </summary>
        public String Done { get; set; }
       
        /// <summary>
        /// 超时多久
        /// </summary>
        public int? OverTime { get; set; }

        /// <summary>
        /// 构造函数
        /// </summary>
        public WorkOutTimeEntity()
        {
            this.Days = null;
            this.Days1 = null;
            this.Days2 = null;
            this.Hours = null;
            this.Hours1 = null;
            this.Hours2 = null;
            this.Minutes = null;
            this.Minutes1 = null;
            this.Minutes2 = null;
            this.OverTime = null;
        }

        /// <summary>
        /// 从数据行读取
        /// </summary>
        /// <param name="dataRow">数据行</param>
        protected override BaseEntity GetFrom(IDataRow dataRow)
        {
            this.Guid = BusinessLogic.ConvertToString(dataRow[WorkOutTimeTable.FieldGuid]);
            this.WorkFlowId = BusinessLogic.ConvertToString(dataRow[WorkOutTimeTable.FieldWorkFlowId]);
            this.WorkTaskId = BusinessLogic.ConvertToString(dataRow[WorkOutTimeTable.FieldWorkTaskId]);
            this.Name = BusinessLogic.ConvertToString(dataRow[WorkOutTimeTable.FieldName]);
            this.Days = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldDays]);
            this.Hours = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldHours]);
            this.Minutes = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldMinutes]);
            this.Days1 = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldDays1]);
            this.Hours1 = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldHours1]);
            this.Minutes1 = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldMinutes1]);
            this.Days2 = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldDays2]);
            this.Hours2 = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldHours2]);
            this.Minutes2 = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldMinutes2]);
            this.Done = BusinessLogic.ConvertToString(dataRow[WorkOutTimeTable.FieldDone]);
            this.OverTime = BusinessLogic.ConvertToNullableInt(dataRow[WorkOutTimeTable.FieldOverTime]);
            return this;
        }
    }
}
